name: CI Pipeline
run-name: CI Pipeline
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string
      appType:
        required: true
        type: string
jobs:
    code-checkout:
      runs-on: self-hosted
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            repository: raghudevopsb82/roboshop-${{ inputs.component }}

    app-dependencies:
      runs-on: self-hosted
      needs: code-checkout
      steps:
        - name: Download Dependency
          run: |
            if [ ${{ inputs.appType }} == maven ]; then
              mvn clean package
            elif [ ${{ inputs.appType }} == nodejs ];then
              npm install
            elif [ ${{ inputs.appType }} == python ]; then
              pip3 install -r requirements.txt
            fi


    static-code-analysis:
      runs-on: self-hosted
      needs: app-dependencies
      steps:
        - name: Download Dependency
          run: ls -l

    unit-tests:
      runs-on: self-hosted
      needs: static-code-analysis
      steps:
        - name: Download Dependency
          run: ls -l

    build-container-image:
      runs-on: self-hosted
      needs: unit-tests
      steps:
        - name: Download Dependency
          run: ls -l

    push-to-image-registry:
      runs-on: self-hosted
      needs: build-container-image
      steps:
        - name: Download Dependency
          run: ls -l





