name: Terraform
on:
  workflow_call:
    inputs:
      action:
        required: true
        type: string
    secrets:
      VAULT_TOKEN:
        required: true
jobs:
    apply:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4

        - name: Retrieve Vault Secrets
          id: import-secrets
          uses: hashicorp/vault-action@v2
          with:
            url: http://vault-internal.azdevopsb82.online:8200
            token: ${{ secrets.VAULT_TOKEN }}
            secrets: |
              infra/github-actions *;

        - run: make dev-${{ inputs.action }} vault_token=${{ secrets.VAULT_TOKEN }}



